syntax = "proto3";

option csharp_namespace = "AppServer.API";

import "google/protobuf/wrappers.proto";


// Generic failure message containing business logic failure information.
message Failure {
    google.protobuf.Int32Value code = 1; // Failure code (nullable), Grpc.Core.StatusCode
    string message = 2; // Failure message

    repeated FailedProperty failed_properties = 3;
}

message FailedProperty {
    google.protobuf.Int32Value code = 1; // Failure code (nullable), Grpc.Core.StatusCode
    string message = 2;
    string property_name = 3; 
}